#!/usr/bin/perl

$flag = $ARGV[0];

$spotifyrunning = `pidof spotify` ne "";


# TO PLAY OR PAUSE
if ($flag eq "-u"){
    if ($spotifyrunning) {
        `timeout 1 playerctl play-pause`;
    } else { # cmus
        `/usr/local/bin/cmus-remote -u`;
    }
}

# NEXT
if ($flag eq "-n"){
    if ($spotifyrunning) {
        `timeout 1 playerctl next`;
    } else { # cmus
        `/usr/local/bin/cmus-remote -n`;
    }
}

# PREVIOUS
if ($flag eq "-r"){
    if ($spotifyrunning) {
        `timeout 1 playerctl previous`;
    } else { # cmus
        `/usr/local/bin/cmus-remote -r`;
    }
}

