
(defvar /device/ "pixel")

; picture folders to _PULL_
(defvar /pic-folders-to-pull/ (list
  "Instagram"
  "Messages"
  "Screenshots"
  "Twitter"
  "Reddit"
  "Boost"
))

; picture folders to sync (push)
(defvar /pic-folders-to-push/ (list
  "Andromahi"
  "Art Ideas"
  "Cool Pictures"
  "Cute Animals"
  "Humour"
  "My Art"
  "Wallpapers"
))


; playlists to sync (push)
(defvar /playlists-to-push/ (list
  "A Bunch of New Songs"
  "A Tribe Called Quest"
  "Against Me!"
  "Anna Vissi"
  "And Also The Trees"
  "Anti-Flag"
  "Aquabats!"
  "Arcade Fire"
  "Architecture in Helsinki"
  "Arts and Crafts"
  "Asylum Party"
  "Bachata"
  "Bad Religion"
  "Beach Boys"
  "Beirut"
  "Billy Joel"
  "Bjork"
  "Black Moth Super Rainbow"
  "Bright Eyes"
  "Broken Social Scene"
  "Busta Rhymes"
  "Caifanes"
  "Capos Are Indie"
  "Capos Are Staging"
  "Catalonia Invades"
  "Clan of Xymox - Frozen Autumn"
  "Clash City Rockers"
  "Climatewave and Late Nights"
  "Cocteau Twins"
  "Cold and New"
  "Coldwave"
  "Computer Magic"
  "Contemporary Post-Punk"
  "Crack Rock Steady"
  "Crusty Punk"
  "Crystal Castles"
  "Crystal Stilts"
  "Darkwave"
  "David Bowie"
  "DDT"
  "Dead Can Dance"
  "Dead Prez"
  "Décima Víctima"
  "De La Soul"
  "Depeche Mode"
  "Disco Flies Bananas"
  "Døpe 80s Tracks"
  "Døpe 90s Dance Hits"
  "Echo and The Bunnymen"
  "Editors"
  "Elliott Smith"
  "Elton John"
  "El Último Vecino"
  "Elvis Costello"
  "Feist"
  "Forwards and Bachwards"
  "Frank Gambale"
  "Frank _Just Frank_"
  "Frou Frou"
  "Gang of Four"
  "Gary Numan"
  "Goth"
  "Greek, Not Otherwise Specified"
  "Guided By Voices"
  "Gustavo Cerati"
  "Hari and Aino"
  "Hello Saferide"
  "In The Heights"
  "Indie Pop"
  "Interpol"
  "Intocable"
  "Johnny F----ng Marr"
  "Joy Division"
  "Keane"
  "KRS-One"
  "K-The-I"
  "KAITOYΛA"
  "Ladytron"
  "Laibach"
  "Language Exchange"
  "Little Nemo"
  "Lowlife"
  "Manu Chao"
  "Math and Physics Club"
  "Metric"
  "Michael Jackson"
  "Mitropanos Mania"
  "Morrissey"
  "Mustard Plug"
  "My Bloody Valentine"
  "New Order"
  "NOFX"
  "Northern Portrait"
  "Oppenheimer Analysis"
  "Party Jams"
  "Peter Murphy"
  "Peter Tosh"
  "Pet Shop Boys"
  "Pimsleur Greek"
  "Pink Turns Blue"
  "Public Enemy"
  "Rakim"
  "Rancid"
  "Reading Time"
  "Red Lorry Yellow Lorry"
  "REM"
  "Ride"
  "Rilo Kiley"
  "Rosetta Stone"
  "Sad Lovers and Giants"
  "Say Hi _To Your Mom_"
  "Seapony"
  "Shakira"
  "Shoegaze Space Station"
  "Sigur Rós"
  "Silvio Rodriguez"
  "Siouxsie Sioux"
  "Ska"
  "SLC Punk"
  "Slowdive"
  "Smashing Pumpkins"
  "Soda Stereo"
  "Someone Still Loves You Boris Yeltsin"
  "Systems Of Romance"
  "Talking Heads"
  "The Alternative"
  "The Chameleons"
  "The Church"
  "The Coup"
  "The Divine Comedy"
  "The Doors"
  "The Essentials I"
  "The Fairways"
  "The Gimme Gimmes"
  "The Lawrence Arms"
  "The Left Banke"
  "The Lucy Show"
  "The Magnetic Fields"
  "The National"
  "The New Pornographers"
  "The Pains Of Being Pure At Heart"
  "The Police"
  "The Psychedelic Furs"
  "The Ramones"
  "The Shins"
  "The Sisters of Mercy"
  "The Sound"
  "The Stone Roses"
  "The Strokes"
  "The Teardrop Explodes"
  "The Who"
  "They Might Be Giants"
  "Thieves Like Us"
  "Tokyo Police Club"
  "Travlin Music Bustinyaassstyle"
  "Twee"
  "U2"
  "Vaporwave Selects"
  "Vaporwave Transmissions"
  "Wu-Tang Killa Bees"
  "Young Galaxy"
  "_temporary"
  ))

