#!/data/data/com.termux/files/usr/bin/bash

export ZME=`whoami`

echo "pixel4a"

if [[ $ZME = 'u0_a225' ]]
then
    echo "pixel4a"
elif [[ $ZME = 'u0_a280' ]]
then
    echo "goodtablet"
else
    echo "unknown"
fi
