#!/data/data/com.termux/files/usr/bin/bash

export ZME=`whoami`

if [[ $ZME = 'u0_a225' ]]
then
    echo "pixel4a"
elif [[ $ZME = 'u0_a280' ]]
then
    echo "goodtablet"
elif [[ $ZME = 'u0_a322' ]]
then
    echo "grandtablet"
else
    echo "unknown"
fi
